import { useEffect, useMemo, useState } from "react";
import { useConsultationChat, type ChatMessage } from "@/lib/useConsultationChat";
import { fetchOpeningSuggestions } from "@/lib/api";
import { messagesKey } from "@/lib/storage";
import type { ComprehensiveTrainingPlan } from "@/lib/types";
import { ChatThread, Chips, ChatComposer } from "./ChatThread";

export function ChatIntake({
  consultationId,
  petName,
  ownerFirst,
  planReady,
  onGenerate,
  onViewPlan,
  onPlanProposed,
}: {
  consultationId: string;
  petName: string;
  ownerFirst: string;
  /** True once a plan exists (autonomously proposed in chat, or finalized). */
  planReady: boolean;
  /** Manual "skip the questions" path -> POST /finalize. */
  onGenerate: () => void;
  onViewPlan: () => void;
  /** The agent proposed a plan mid-conversation. */
  onPlanProposed: (plan: ComprehensiveTrainingPlan) => void;
}) {
  const [input, setInput] = useState("");

  // A friendly greeting shown client-side. (It is not persisted in the DB; the
  // backend builds LLM context from the stored messages once the user replies.)
  const initialMessages = useMemo<ChatMessage[]>(
    () => [
      {
        id: "intro",
        role: "assistant",
        text: `Hi ${ownerFirst} — thanks for bringing ${petName} in. I've got the basics. To start, which of these sound closest to what's been worrying you most? Pick any that apply, or just type below.`,
      },
    ],
    [ownerFirst, petName]
  );

  const { messages, status, send: sendMessage } = useConsultationChat({
    consultationId,
    initialMessages,
    onPlan: onPlanProposed,
    storageKey: messagesKey(consultationId, "intake"),
  });

  // Opening chips are generated by the LLM from the owner's stated concern.
  const [chips, setChips] = useState<string[]>([]);
  useEffect(() => {
    let active = true;
    void fetchOpeningSuggestions(consultationId).then((s) => {
      if (active) setChips(s);
    });
    return () => {
      active = false;
    };
  }, [consultationId]);

  const isStreaming = status !== "ready";
  const ready = status === "ready";
  const userTurns = messages.filter((m) => m.role === "user").length;

  function send(text: string) {
    const t = text.trim();
    if (!t || isStreaming) return;
    setInput("");
    void sendMessage(t);
  }

  return (
    <div
      style={{
        maxWidth: 720,
        margin: "0 auto",
        padding: "24px 18px",
        display: "flex",
        flexDirection: "column",
        height: "calc(100vh - 63px)",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }}>
        <div>
          <div style={{ fontFamily: "var(--font-head)", fontSize: 18, fontWeight: 600 }}>
            Your consultant
          </div>
        </div>
      </div>

      <ChatThread messages={messages} typing={status === "submitting"} />

      <div style={{ paddingTop: 12 }}>
        {ready && (planReady || userTurns >= 3) && (
          <div style={{ textAlign: "center", padding: "6px 0 14px" }}>
            <button
              onClick={planReady ? onViewPlan : onGenerate}
              style={{
                background: "var(--accent)",
                color: "var(--accent-ink)",
                border: "none",
                fontSize: 16,
                fontWeight: 700,
                padding: "15px 30px",
                borderRadius: 99,
                boxShadow: "0 6px 20px -8px var(--accent)",
              }}
            >
              {planReady ? "View" : "Generate"} {petName}&apos;s plan →
            </button>
          </div>
        )}

        {ready && userTurns === 0 && chips.length > 0 && (
          <Chips options={chips} onPick={send} multiSelect />
        )}

        <ChatComposer
          value={input}
          onChange={setInput}
          onSend={() => send(input)}
          placeholder="Type your answer…"
          disabled={isStreaming}
        />
      </div>
    </div>
  );
}
